name: Spring Petclinic CI (Assignment-2)

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: nikhilk7/github-actions-template/.github/workflows/reusable-docker-build.yaml@main

    with:
      image_name: spring-petclinic
      build_command: ./mvnw clean package
      dockerfile_path: Dockerfile

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}